         COPY  IAVL
         COPY  IAV2
         COPY  IFFO
         COPY  IFMG
         COPY  IIFO
         COPY  IIND
         COPY  IINF
         COPY  IINS
         COPY  ILOG
         COPY  IPRS
         COPY  IPSS
         COPY  IREX
         COPY  ISTB
         COPY  ISTR
         COPY  IST1
         COPY  IST2
         COPY  IST3
         COPY  IST4
         COPY  IST5
         COPY  IST6
         COPY  IST7
         COPY  IST8
         COPY  ITFO
         COPY  ITOK
         COPY  IUSS
