# Makefile for SAMPLE11
.RECIPEPREFIX = -   # use - as the recipe prefix char

hlq        := # <=== enter your sample hlq here
mask       := $(hlq).N*
nextnr     := ${function NEXTNR,$(mask)}

.PHONY ALLOC
ALLOC :
- nextds := $(hlq).N$(nextnr)
- CALL TSOCMD ALLOC DATASET('$(nextds)') NEW RECFM(F,B) LRECL(80)\
-             CYLINDERS SPACE(1,1) DSORG(PO) DSNTYPE(LIBRARY)
- CALL TSOCMD FREE DATASET('$(nextds)')
