# Makefile for SAMPLE10
.RECIPEPREFIX = -   # use - as the recipe prefix char

hlq        := # <=== enter your sample hlq here
template   := $(hlq).TEMPLATE(WHYJCL)
resolves   := ${addpdsname $(hlq).CNTL, \
                 ${memberlist $(hlq).CNTL, RESOL} }
temppds    := ${function TEMPPDS}

.PHONY UPDATE
UPDATE : $(resolves)

$(resolves) : 1
- CALL UPDCOPY DSIN($(template)) DSOUT($(temppds)($%)) UPDWITH($@)
- CALL SUBMIT $(temppds)($%)
