# Makefile for SAMPLE09
.RECIPEPREFIX = -   # use - as the recipe prefix char

hlq     := # <=== enter your sample hlq here
srcpds  := $(hlq).SRCPDS
tgtpds  := $(hlq).TGTPDS
newmems := $(memberlist $(srcpds))
tgts    := $(addpdsname $(tgtpds), $(newmems))

.PHONY DEPLOY
DEPLOY : $(tgts)

$(tgts) : $(addpdsname $(srcpds), $%)
- CALL IEBCOPY PDSIN($(srcpds)) PDSOUT($(tgtpds)) MEMBER($%)